nodeLinker: node-modules

# Disable Plug'n'Play to avoid filesystem issues with Next.js
pnpMode: loose

# Enable caching for better performance
enableGlobalCache: false

# Telemetry settings
enableTelemetry: false 